version: '3'

services:
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - ./api:/app
    ports:
      - 3010:3000
    tty:
      true
    depends_on:
      - db
      - redis
      - minio
  db:
    restart: always
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./minio/data:/data
    command: server --console-address ":9001" /data
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set test-minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb test-minio/test-bucket;
      /usr/bin/mc policy set public test-minio/test-bucket;
      "